name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Determine composer cache directory
      id: determine-composer-cache-directory
      run: echo "::set-output name=composer_cache_dir::$(composer config cache-dir)"

    - name: Cache dependencies installed with composer
      uses: actions/cache@v3
      with:
        path: ${{ steps.determine-composer-cache-directory.outputs.composer_cache_dir }}
        key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}

    - name: Composer install dependencies
      run: composer install

    - name: Run phpstan
      run: composer stan

    - name: Run phpcs
      run: composer phpcs

    - name: Run phpunit
      run: composer test
